LangString addOrReinstall ${LANG_ROMANIAN} "Adaugă/Reinstalează componente"
LangString alreadyInstalled ${LANG_ROMANIAN} "Deja instalat"
LangString alreadyInstalledLong ${LANG_ROMANIAN} "${PRODUCTNAME} ${VERSION} este deja instalat. Alegeți operația dorită și apăsați Înainte pentru a continua."
LangString appRunning ${LANG_ROMANIAN} "{{product_name}} rulează! Închideți-l mai întâi, apoi încercați din nou."
LangString appRunningOkKill ${LANG_ROMANIAN} "{{product_name}} rulează!$\nApăsați OK pentru a-l închide forțat"
LangString chooseMaintenanceOption ${LANG_ROMANIAN} "Alegeți operația de întreținere de efectuat."
LangString choowHowToInstall ${LANG_ROMANIAN} "Alegeți cum doriți să instalați ${PRODUCTNAME}."
LangString createDesktop ${LANG_ROMANIAN} "Creează o scurtătură pe desktop"
LangString dontUninstall ${LANG_ROMANIAN} "Nu dezinstala"
LangString dontUninstallDowngrade ${LANG_ROMANIAN} "Nu dezinstala (revenirea la o versiune anterioară este dezactivată)"
LangString failedToKillApp ${LANG_ROMANIAN} "Nu s-a putut închide {{product_name}}. Închideți-l mai întâi, apoi încercați din nou"
LangString installingWebview2 ${LANG_ROMANIAN} "Se instalează WebView2..."
LangString newerVersionInstalled ${LANG_ROMANIAN} "O versiune mai nouă a ${PRODUCTNAME} este deja instalată!"
LangString older ${LANG_ROMANIAN} "mai veche"
LangString olderOrUnknownVersionInstalled ${LANG_ROMANIAN} "O versiune $R4 a ${PRODUCTNAME} este instalată."
LangString silentDowngrades ${LANG_ROMANIAN} "Revenirea la o versiune anterioară este dezactivată pentru acest program de instalare."
LangString unableToUninstall ${LANG_ROMANIAN} "Dezinstalarea nu este posibilă!"
LangString uninstallApp ${LANG_ROMANIAN} "Dezinstalează ${PRODUCTNAME}"
LangString uninstallBeforeInstalling ${LANG_ROMANIAN} "Dezinstalează înainte de instalare"
LangString unknown ${LANG_ROMANIAN} "necunoscută"
LangString webview2AbortError ${LANG_ROMANIAN} "Instalarea WebView2 a eșuat!"
LangString webview2DownloadError ${LANG_ROMANIAN} "Eroare: descărcarea WebView2 a eșuat - $0"
LangString webview2DownloadSuccess ${LANG_ROMANIAN} "Programul de instalare WebView2 a fost descărcat cu succes"
LangString webview2Downloading ${LANG_ROMANIAN} "Se descarcă programul de instalare WebView2..."
LangString webview2InstallError ${LANG_ROMANIAN} "Eroare: instalarea WebView2 a eșuat cu codul $1"
LangString webview2InstallSuccess ${LANG_ROMANIAN} "WebView2 a fost instalat cu succes"
LangString deleteAppData ${LANG_ROMANIAN} "Șterge datele aplicației"
